#!/bin/sh

# Exit if any subcommand fails
set -e

docker-compose up -d

COMPOSE="docker-compose exec app"

printf "\nRunning tasks\n\n"
$COMPOSE lucky db.drop
$COMPOSE lucky db.create
$COMPOSE lucky db.migrate

if [ $# -eq 0 ]
then
    # Integratioin test various tasks
    printf "\nRolling back to 20180802180356\n"
    $COMPOSE lucky db.rollback_to 20180802180356
    printf "\nRolling back remainder\n"
    $COMPOSE lucky db.rollback_all
    $COMPOSE lucky db.migrate.one
    $COMPOSE lucky db.migrate
    $COMPOSE lucky db.migrations.status
    $COMPOSE lucky db.reset
fi

printf "\nRunning specs\n\n"
$COMPOSE crystal spec "$@"

if [ $# -eq 0 ]
then
    printf "\nChecking that tasks build correctly\n\n"
    $COMPOSE shards build
    
    printf "\nChecking code formatting\n\n"
    if ! $COMPOSE crystal tool format --check src spec config > /dev/null; then
        printf "\nCode is not formatted.\n"
        printf "\nFormat the code with: docker-compose run --rm app crystal tool format src spec config\n\n"
        exit 1
    fi
fi

docker-compose down
